### ISSUE TITLE
Suggestion/Feature Request: Do not use a hardcoded path for glpk

### ISSUE THREAD

**Issue by bartlett-m** [Scott1903/satisfactory_planner#1]
If the path to glpk is omitted, the program can automatically determine it from the system's PATH environment variable.  On Linux, this will mean that glpk will automatically load if installed via a system's package manager, and [on Windows it is possible to edit the PATH environment variable](https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/#how-to-edit-environment-variables) to include your installation of glpk.

This removes the need for users to manually edit the code of the application.

**Comment by mylesbartlett72** [comment]
also thank you so much for making and maintaining this program!

**Comment by Scott1903** [comment]
Thanks for the feedback!  I appreciated it.

**Comment by mylesbartlett72** [comment]
> also thank you so much for making and maintaining this program!

i somehow managed to use both my school and main account to reply to this (oops!)
